package com.pep.sdk.pap.model;

/**
 * Enumeration of operations that can be performed on entities within the PAP.
 */
public enum PapEvent {
    TENANT_CREATED,
    TENANT_UPDATED,
    TENANT_DELETED,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    RESOURCE_TYPE_CREATED,
    RESOURCE_TYPE_UPDATED,
    RESOURCE_TYPE_DELETED,
    RESOURCE_INSTANCE_CREATED,
    RESOURCE_INSTANCE_UPDATED,
    RESOURCE_INSTANCE_DELETED,
    TOPIC_CREATED,
    TOPIC_UPDATED,
    TOPIC_DELETED,
    TOPIC_ACCESS_CREATED,
    TOPIC_ACCESS_UPDATED,
    TOPIC_ACCESS_DELETED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    USER_GROUP_INSTANCE_CREATED,
    USER_GROUP_INSTANCE_UPDATED,
    USER_GROUP_INSTANCE_DELETED
}
